difficulty:
  # This determines the EXTRA mob health in relation to the player's power level.
  # The forumla is: mob health = ( ( defense-5 ) / divide-by ) * base_health + base_health
  divide-by: 92
  hostile-only: true
  player-distance: 512
  use-power-level: false # if false, it will use defense level
  random:
    enabled: true
    amount: 0.10 # Randomly vary the player's power level by this percentage, e.g: 0.10 = 10%
natural-reason-only: true
